CREATE TABLE IF NOT EXISTS catalogue_admin (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

INSERT INTO catalogue_admin (username, password) VALUES
-- student: Password1!
('student', '$2y$10$Yl1WFzwD6bSxeOR1ISdkCejkI.vXt00Bjalw44JaB0ErWpJ0iCzY2'),

-- Instructor: Test123!
('instructor', '$2y$10$hPZtTmcFYytMXtIBMTFeReOiSvRsm1upFFJYpviAFKMSZehXXNkyu');


CREATE TABLE ttun_catalogue (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    title VARCHAR(20) NOT NULL,
    element VARCHAR(20) NOT NULL,
    age INT NOT NULL,
    `rank` VARCHAR(1) NOT NULL,
    `class` VARCHAR(20) NOT NULL,
    faction VARCHAR(50) NOT NULL,
    image_filename VARCHAR(255) DEFAULT NULL
);

INSERT INTO ttun_catalogue (name, title, element, age, `rank`, `class`, faction, image_filename)
VALUES 
('Bianca', 'Stigmata', 'Physical', 25, 'S', 'Attacker', 'Punishing Force', 'stigmata.webp'),
('Lee', 'Hyperreal', 'Fire', 18, 'S', 'Attacker', 'Gray Raven', 'hyperreal.webp'),
('Lucia', 'Crimson Weave', 'Lightning', 17, 'S', 'Attacker', 'Ascendant', 'crimsonweave.webp'),
('Alisa', 'Echo', 'Physical', 16, 'S', 'Amplifier', 'Unknown', 'echo.webp'),
('Lamia', 'Lost Lullaby', 'Dark', 15, 'S', 'Attacker', 'Ascendant', 'lostlullaby.webp'),
('Qu', 'Shukra', 'Ice', 18, 'S', 'Attacker', 'Kowloong Chamber of Commerce', 'shukra.webp'),
('Luna', 'Oblivion', 'Nihil', 16, 'S', 'Annihilator', 'Ascendant', 'oblivion.webp'),
('Lucia', 'Pyroath', 'Fire', 17, 'S', 'Attacker', 'Gray Raven', 'pyroath.webp'),
('Ishmael', 'Parhelion', 'Nihil', 0, 'S', 'Observer', 'Unknown', 'parhelion.webp'),
('Vera', 'Geiravor', 'Fire', 17, 'S', 'Amplifier', 'Cerberus', 'geiravor.webp'),
('Lucia', 'Crimson Abyss', 'Physical', 17, 'S', 'Attacker', 'Ascendant', 'crimsonabyss.webp'),
('Liv', 'Empyrea', 'Fire', 16, 'S', 'Amplifier', 'Gray Raven', 'empyrea.webp'),
('Karenina', 'Scire', 'Dark', 16, 'S', 'Attacker', 'Engineering Force', 'scire.webp'),
('Bianca', 'Veritas', 'Lightning', 25, 'S', 'Attacker', 'Purifying Force', 'veritas.webp'),
('Vera', 'Garnet', 'Lightning', 17, 'S', 'Tank', 'Cerberus', 'garnet.webp'),
('Watanabe', 'Epitaph', 'Fire', 26, 'S', 'Tank', 'Forsaken', 'epitaph.webp'),
('Selena', 'Capriccio', 'Dark', 20, 'S', 'Amplifier', 'World Government Association of Art', 'capriccio.webp'),
('Ayla', 'Kaleido', 'Ice', 20, 'S', 'Amplifier', 'Iris Warbler', 'kaleido.webp'),
('Jetavie', 'Daybreak', 'Dark', 0, 'S', 'Attacker', 'Unknown', 'daybreak.webp'),
('Nanami', 'Startrail', 'Lightning', 0, 'S', 'Tank', 'Church of Machina', 'startrail.webp'),
('Lucia', 'Dawn', 'Lightning', 17, 'A', 'Attacker', 'Gray Raven', 'dawn.webp'),
('Liv', 'Lux', 'Lightning', 16, 'A', 'Support', 'Gray Raven', 'lux.webp'),
('Watanabe', 'Nightblade', 'Physical', 19, 'A', 'Attacker', 'Forsaken', 'nightblade.webp'),
('Karenina', 'Blast', 'Physical', 20, 'A', 'Attacker', 'Engineering Force', 'blast.webp'),
('Vera', 'Rozen', 'Dark', 17, 'A', 'Support', 'Cerberus', 'rozen.webp');


CREATE TABLE IF NOT EXISTS images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    catalogue_id INT NOT NULL,
    filename VARCHAR(255) NOT NULL,
    filetype VARCHAR(50),
    filesize INT,
    full_path VARCHAR(255) NOT NULL,
    thumb_path VARCHAR(255) NOT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (catalogue_id) REFERENCES ttun_catalogue(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tags (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tag VARCHAR(50) NOT NULL UNIQUE
);

-- This was generated by AI to tell me how to insert values from another table without writing it all out manually 
/* This is my create tags table:
CREATE TABLE IF NOT EXISTS tags (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tag VARCHAR(50) NOT NULL UNIQUE
);

I want to add the table columns element, `rank`, `class`, and faction from ttun_catalogue without manually inputting them */

INSERT IGNORE INTO tags (tag)
SELECT DISTINCT CAST(element AS CHAR) FROM ttun_catalogue
UNION
SELECT DISTINCT CAST(`rank` AS CHAR) FROM ttun_catalogue
UNION
SELECT DISTINCT CAST(`class` AS CHAR) FROM ttun_catalogue
UNION
SELECT DISTINCT CAST(faction AS CHAR) FROM ttun_catalogue;

-- end of ai generated code

CREATE TABLE IF NOT EXISTS catalogue_tags (
    catalogue_id INT NOT NULL,
    tag_id INT NOT NULL,
    PRIMARY KEY (catalogue_id, tag_id),
    FOREIGN KEY (catalogue_id) REFERENCES ttun_catalogue(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);

-- also generated by ai when i prompted that io don't want to add tags manually to already added characters
INSERT IGNORE INTO catalogue_tags (catalogue_id, tag_id)
SELECT c.id, t.id
FROM ttun_catalogue c
JOIN tags t ON t.tag = c.element;

INSERT IGNORE INTO catalogue_tags (catalogue_id, tag_id)
SELECT c.id, t.id
FROM ttun_catalogue c
JOIN tags t ON t.tag = c.rank;

INSERT IGNORE INTO catalogue_tags (catalogue_id, tag_id)
SELECT c.id, t.id
FROM ttun_catalogue c
JOIN tags t ON t.tag = c.class;

INSERT IGNORE INTO catalogue_tags (catalogue_id, tag_id)
SELECT c.id, t.id
FROM ttun_catalogue c
JOIN tags t ON t.tag = c.faction;
-- end of ai generated code